spring:
  application:
    name: events

  profiles:
    active: dev

jwt:
  key: "4b376edfde6c89d86244b37e6604446b21b846185857e362b094f4cc8b370abe"
  expiration: 86400
  refresh_token:
    expiration: 604800



cloud:
  aws:
    credentials:
      access-key: AKIA5IJOWVZLUMBEUTEX
      secret-key: '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'
    region:
      static: us-east-1
    bucket: bakermhajna


