spring:

  datasource:
    url: jdbc:mysql://events.cr4oiiwkm0p1.us-east-1.rds.amazonaws.com:3306/devdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Baker554422
    hikari:
      maxLifetime: 1800000
      idleTimeout: 600000
      connectionTestQuery: SELECT 1
      maximumPoolSize: 5
      minimumIdle: 2


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG